#!/usr/bin/env python3
"""Add the missing Android namespace to the tdlib Flutter plugin.

The tdlib 1.6.0 package does not declare an Android Gradle namespace, which
breaks release builds with newer Android Gradle Plugin versions generated by
recent Flutter SDKs. This script patches the local pub-cache copy after
`flutter pub get`.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path


DEFAULT_NAMESPACE = "org.drinkless.tdlib.flutter"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--pub-cache",
        type=Path,
        default=Path(os.environ.get("PUB_CACHE", Path.home() / ".pub-cache")),
        help="Flutter pub cache directory. Defaults to PUB_CACHE or ~/.pub-cache.",
    )
    args = parser.parse_args()

    build_files = sorted(args.pub_cache.glob("hosted/*/tdlib-*/android/build.gradle"))
    build_files.extend(sorted(args.pub_cache.glob("hosted/*/tdlib-*/android/build.gradle.kts")))
    if not build_files:
        print(f"tdlib Android Gradle file was not found under {args.pub_cache}", file=sys.stderr)
        return 1

    for build_file in build_files:
        patch_build_file(build_file)
    return 0


def patch_build_file(build_file: Path) -> None:
    text = build_file.read_text(encoding="utf-8")
    if re.search(r"^\s*namespace\b", text, flags=re.MULTILINE):
        print(f"{build_file} already declares an Android namespace")
        return

    namespace = namespace_from_manifest(build_file.parent) or DEFAULT_NAMESPACE
    if build_file.suffix == ".kts":
        namespace_line = f'    namespace = "{namespace}"'
    else:
        namespace_line = f'    namespace "{namespace}"'

    patched, replacements = re.subn(
        r"(?m)^android\s*\{\s*$",
        f"android {{\n{namespace_line}",
        text,
        count=1,
    )
    if replacements != 1:
        raise SystemExit(f"Could not find android block in {build_file}")

    build_file.write_text(patched, encoding="utf-8")
    print(f"Added Android namespace '{namespace}' to {build_file}")


def namespace_from_manifest(android_dir: Path) -> str | None:
    manifest = android_dir / "src" / "main" / "AndroidManifest.xml"
    if not manifest.exists():
        return None
    match = re.search(
        r"\bpackage\s*=\s*['\"]([^'\"]+)['\"]",
        manifest.read_text(encoding="utf-8"),
    )
    return match.group(1) if match else None


if __name__ == "__main__":
    raise SystemExit(main())
