#!/usr/bin/env python3
"""Make the tdlib Flutter plugin compatible with current Android builds.

The tdlib 1.6.0 package does not declare an Android Gradle namespace, which
breaks release builds with newer Android Gradle Plugin versions generated by
recent Flutter SDKs. It also compiles the plugin against a current Android SDK;
the package otherwise stays on API 31 while its AndroidX dependencies require
API 34 or newer. This script patches the local pub-cache copy after
``flutter pub get``.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path


DEFAULT_NAMESPACE = "org.drinkless.tdlib.flutter"
DEFAULT_COMPILE_SDK = 36


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--pub-cache",
        type=Path,
        default=Path(os.environ.get("PUB_CACHE", Path.home() / ".pub-cache")),
        help="Flutter pub cache directory. Defaults to PUB_CACHE or ~/.pub-cache.",
    )
    parser.add_argument(
        "--compile-sdk",
        type=int,
        default=DEFAULT_COMPILE_SDK,
        help=f"Android SDK used to compile tdlib. Defaults to {DEFAULT_COMPILE_SDK}.",
    )
    args = parser.parse_args()
    if args.compile_sdk < 34:
        parser.error("--compile-sdk must be 34 or newer")

    build_files = sorted(args.pub_cache.glob("hosted/*/tdlib-*/android/build.gradle"))
    build_files.extend(sorted(args.pub_cache.glob("hosted/*/tdlib-*/android/build.gradle.kts")))
    if not build_files:
        print(f"tdlib Android Gradle file was not found under {args.pub_cache}", file=sys.stderr)
        return 1

    for build_file in build_files:
        patch_build_file(build_file, args.compile_sdk)
    return 0


def patch_build_file(build_file: Path, compile_sdk: int = DEFAULT_COMPILE_SDK) -> None:
    text = build_file.read_text(encoding="utf-8")
    original = text

    if re.search(r"^\s*namespace\b", text, flags=re.MULTILINE):
        print(f"{build_file} already declares an Android namespace")
    else:
        namespace = namespace_from_manifest(build_file.parent) or DEFAULT_NAMESPACE
        if build_file.suffix == ".kts":
            namespace_line = f'    namespace = "{namespace}"'
        else:
            namespace_line = f'    namespace "{namespace}"'

        text, replacements = re.subn(
            r"(?m)^android\s*\{\s*$",
            f"android {{\n{namespace_line}",
            text,
            count=1,
        )
        if replacements != 1:
            raise SystemExit(f"Could not find android block in {build_file}")
        print(f"Added Android namespace '{namespace}' to {build_file}")

    text, previous_sdk = patch_compile_sdk(text, build_file, compile_sdk)

    if text == original:
        print(f"{build_file} already uses a compatible Android build configuration")
        return

    build_file.write_text(text, encoding="utf-8")
    if previous_sdk is None:
        print(f"Set Android compile SDK to {compile_sdk} in {build_file}")
    elif previous_sdk < compile_sdk:
        print(
            f"Raised Android compile SDK from {previous_sdk} to {compile_sdk} "
            f"in {build_file}"
        )


def patch_compile_sdk(text: str, build_file: Path, target: int) -> tuple[str, int | None]:
    """Set a numeric compile SDK without downgrading a newer declaration."""

    numeric_pattern = re.compile(
        r"(?m)^(?P<prefix>\s*compileSdk(?:Version)?(?:\s*=\s*|\s*\(\s*|\s+))"
        r"(?P<version>\d+)(?P<suffix>\s*\)?[^\r\n]*)$"
    )
    match = numeric_pattern.search(text)
    if match:
        current = int(match.group("version"))
        if current >= target:
            return text, current
        replacement = f'{match.group("prefix")}{target}{match.group("suffix")}'
        return text[: match.start()] + replacement + text[match.end() :], current

    declaration_pattern = re.compile(r"(?m)^(?P<indent>\s*)compileSdk(?:Version)?\b[^\r\n]*$")
    declaration = declaration_pattern.search(text)
    if declaration:
        indent = declaration.group("indent")
        replacement = (
            f"{indent}compileSdk = {target}"
            if build_file.suffix == ".kts"
            else f"{indent}compileSdkVersion {target}"
        )
        return (
            text[: declaration.start()] + replacement + text[declaration.end() :],
            None,
        )

    sdk_line = (
        f"    compileSdk = {target}"
        if build_file.suffix == ".kts"
        else f"    compileSdkVersion {target}"
    )
    patched, replacements = re.subn(
        r"(?m)^android\s*\{\s*$",
        f"android {{\n{sdk_line}",
        text,
        count=1,
    )
    if replacements != 1:
        raise SystemExit(f"Could not find android block in {build_file}")
    return patched, None


def namespace_from_manifest(android_dir: Path) -> str | None:
    manifest = android_dir / "src" / "main" / "AndroidManifest.xml"
    if not manifest.exists():
        return None
    match = re.search(
        r"\bpackage\s*=\s*['\"]([^'\"]+)['\"]",
        manifest.read_text(encoding="utf-8"),
    )
    return match.group(1) if match else None


if __name__ == "__main__":
    raise SystemExit(main())
